import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { chat } from "../lib/openai.js";
import {
  PATHS,
  SOURCE_LANGUAGE,
  TARGET_LANGUAGES,
  getLanguageName,
} from "../lib/config.js";
import { getCacheHash, setCacheHash, getUICacheKey } from "../lib/cache.js";

function getTargetPath(lang: string): string {
  return path.join(PATHS.uiDir, `${lang}.json`);
}

function getHash(content: string): string {
  return crypto.createHash("md5").update(content).digest("hex");
}

function loadLocale(lang: string): Record<string, string> {
  const filePath = getTargetPath(lang);
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf-8"));
  } catch {
    return {};
  }
}

function saveLocale(lang: string, data: Record<string, string>): void {
  fs.writeFileSync(getTargetPath(lang), JSON.stringify(data, null, 2) + "\n");
}

function generateTypesFile(keys: string[]): void {
  const lines = keys
    .sort()
    .map((key) => `  | "${key}"`)
    .join("\n");

  const content = `// Auto-generated by translate script. Do not edit manually.
// Run \`npm run translate\` to regenerate.

export type UIKey =
${lines};
`;

  fs.writeFileSync(PATHS.uiTypes, content);
}

async function translateUILanguage(
  sourceData: Record<string, string>,
  targetLang: string,
): Promise<void> {
  console.log(`Translating UI to ${getLanguageName(targetLang)}...`);

  const existing = loadLocale(targetLang);
  const newKeys = Object.keys(sourceData).filter(
    (key) => !existing[key] || existing[key] !== sourceData[key],
  );
  const removedKeys = Object.keys(existing).filter(
    (key) => !(key in sourceData),
  );

  if (removedKeys.length > 0) {
    for (const key of removedKeys) {
      delete existing[key];
      console.log(`  🗑 ${key}: Removed`);
    }
  }

  if (newKeys.length === 0) {
    if (removedKeys.length === 0) {
      console.log(`  ✓ All UI strings up to date`);
    }
    saveLocale(targetLang, existing);
    return;
  }

  const toTranslate = sourceData;

  const system = `You are a professional UI translator.
Translate the following UI strings from ${getLanguageName(SOURCE_LANGUAGE)} to ${getLanguageName(targetLang)}.
These are interface labels, navigation items, button text, headings, and short messages.

Guidelines:
- Return a JSON object with the exact same keys but translated values.
- Keep translations concise, natural, and suitable for a software UI.
- Use consistent terminology across related keys (e.g., nav.x, x.title, x.subtitle).
- Do not translate brand names such as "Mandacode".
- Preserve placeholders like {year} exactly as they appear.`;

  const user = `Translate all of these UI strings:

${JSON.stringify(toTranslate, null, 2)}`;

  const response = await chat({
    system,
    user,
    model: "gpt-4o-mini",
    jsonMode: true,
  });
  const translated = JSON.parse(response) as Record<string, string>;

  for (const key of Object.keys(sourceData)) {
    existing[key] = translated[key] || sourceData[key];
  }

  saveLocale(targetLang, existing);
  console.log(`  ✓ Translated ${Object.keys(sourceData).length} strings`);
}

export async function translateUI(): Promise<void> {
  console.log("🌐 Translating UI strings...\n");

  const sourceData = loadLocale(SOURCE_LANGUAGE);
  generateTypesFile(Object.keys(sourceData));

  const sourceJson = JSON.stringify(sourceData, null, 2) + "\n";
  const sourceHash = getHash(sourceJson);

  for (const targetLang of TARGET_LANGUAGES) {
    if (targetLang === SOURCE_LANGUAGE) {
      saveLocale(targetLang, sourceData);
      continue;
    }

    const cacheKey = getUICacheKey(targetLang, "translate");
    const cachedHash = getCacheHash("translate", cacheKey);

    if (cachedHash === sourceHash) {
      console.log(
        `  ✓ ${getLanguageName(targetLang)} UI strings up to date (hash match)`,
      );
      continue;
    }

    await translateUILanguage(sourceData, targetLang);
    setCacheHash("translate", cacheKey, sourceHash);
  }

  console.log("\n✅ UI translation complete!");
}
