import fs from "node:fs";
import path from "node:path";
import { chat } from "../lib/openai.js";
import {
  PATHS,
  SOURCE_LANGUAGE,
  TARGET_LANGUAGES,
  getLanguageName,
} from "../lib/config.js";

function getTargetPath(lang: string): string {
  return path.join(PATHS.uiDir, `${lang}.json`);
}

function loadLocale(lang: string): Record<string, string> {
  const filePath = getTargetPath(lang);
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf-8"));
  } catch {
    return {};
  }
}

function saveLocale(lang: string, data: Record<string, string>): void {
  fs.writeFileSync(getTargetPath(lang), JSON.stringify(data, null, 2) + "\n");
}

function generateTypesFile(keys: string[]): void {
  const lines = keys
    .sort()
    .map((key) => `  | "${key}"`)
    .join("\n");

  const content = `// Auto-generated by translate script. Do not edit manually.
// Run \`npm run translate:ui\` to regenerate.

export type UIKey =
${lines};
`;

  fs.writeFileSync(PATHS.uiTypes, content);
}

async function translateUILanguage(
  sourceData: Record<string, string>,
  targetLang: string,
): Promise<void> {
  console.log(`Translating UI to ${getLanguageName(targetLang)}...`);

  const existing = loadLocale(targetLang);
  const newKeys = Object.keys(sourceData).filter((key) => !existing[key]);
  const removedKeys = Object.keys(existing).filter(
    (key) => !(key in sourceData),
  );

  if (removedKeys.length > 0) {
    for (const key of removedKeys) {
      delete existing[key];
      console.log(`  🗑 ${key}: Removed`);
    }
  }

  if (newKeys.length === 0) {
    if (removedKeys.length === 0) {
      console.log(`  ✓ All UI strings up to date`);
    }
    saveLocale(targetLang, existing);
    return;
  }

  const toTranslate: Record<string, string> = {};
  for (const key of newKeys) {
    toTranslate[key] = sourceData[key];
  }

  const system = `You are a professional translator.
Translate UI strings from ${getLanguageName(SOURCE_LANGUAGE)} to ${getLanguageName(targetLang)}.
Return a JSON object with the same keys but translated values.
Preserve technical terms, brand names, and placeholders like {name}.`;

  const user = `Translate these strings:\n\n${JSON.stringify(toTranslate, null, 2)}`;

  const response = await chat({
    system,
    user,
    model: "gpt-4o-mini",
    jsonMode: true,
  });
  const translated = JSON.parse(response) as Record<string, string>;

  for (const key of newKeys) {
    existing[key] = translated[key] || sourceData[key];
  }

  saveLocale(targetLang, existing);
  console.log(`  ✓ Translated ${newKeys.length} strings`);
}

export async function translateUI(): Promise<void> {
  console.log("🌐 Translating UI strings...\n");

  const sourceData = loadLocale(SOURCE_LANGUAGE);
  generateTypesFile(Object.keys(sourceData));

  for (const targetLang of TARGET_LANGUAGES) {
    if (targetLang === SOURCE_LANGUAGE) continue;
    await translateUILanguage(sourceData, targetLang);
  }

  console.log("\n✅ UI translation complete!");
}
